FROM maven:3.9.9-eclipse-temurin-21 AS build  
WORKDIR /project
COPY . /project/
RUN mvn clean package
EXPOSE 8080
EXPOSE 9401
CMD ["mvn", "exec:java", "-Dexec.mainClass=ttt_api_gateway.infrastructure.APIGatewayMain"]